name: Build and Push container

on:
  push:
    branches: [main]
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
        python: [3.10.13, 3.11.0, 3.11.7, 3.12.1]
        aiida-core: [2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2]
        postgres: [15.1]
        rabbitmq: [3.10.14]
    name: aiida-${{ matrix.aiida-core }}, python-${{ matrix.python }}
    steps:
      - name: Authenticate with harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v4

      - name: Build and Push image to Harbor
        run: |
          docker build ./docker --build-arg BASE_IMAGE=${{ matrix.os }} --build-arg PYTHON_VERSION=${{ matrix.python }} --build-arg AIIDA_VERSION=${{ matrix.aiida-core }} --build-arg PGSQL_VERSION=${{ matrix.postgres }} --build-arg RMQ_VERSION=${{ matrix.rabbitmq }} -t harbor.stfc.ac.uk/biosimulation-cloud/aiida-testbase:$(date +'%Y-%m-%d')-aiida${{ matrix.aiida-core }}-py${{ matrix.python }}
          docker push harbor.stfc.ac.uk/biosimulation-cloud/aiida-testbase:$(date +'%Y-%m-%d')-aiida${{ matrix.aiida-core }}-py${{ matrix.python }}
