name: Build and Push container

on:
  push:
    branches: [main]
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04]
        python: [3.10.13, 3.11.7, 3.12.1]
    name: ubuntu:${{ matrix.os }}, python-${{ matrix.python }}
    steps:
      - name: Authenticate with harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.stfc.ac.uk
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Build and Push image to Harbor
        run: |
          docker build ./docker --build-arg BASE_IMAGE=ubuntu:${{ matrix.os }} --build-arg PYTHON_VERSION=${{ matrix.python }}  -t harbor.stfc.ac.uk/biosimulation-cloud/aiida-testbase:ubuntu${{ matrix.os }}-py${{ matrix.python }}
          docker push harbor.stfc.ac.uk/biosimulation-cloud/aiida-testbase:ubuntu${{ matrix.os }}-py${{ matrix.python }}


